// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_recipes_import_recipe_photosSchema = {
    properties: {
        photos: {
            items: {
                type: 'string',
                format: 'binary'
            },
            type: 'array',
            title: 'Photos'
        },
        language: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Language'
        }
    },
    type: 'object',
    required: ['photos'],
    title: 'Body_recipes-import_recipe_photos'
} as const;

export const DeduplicateMergeSchema = {
    properties: {
        kept: {
            type: 'string',
            title: 'Kept'
        },
        removed: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Removed'
        }
    },
    type: 'object',
    required: ['kept', 'removed'],
    title: 'DeduplicateMerge'
} as const;

export const DeduplicateResponseSchema = {
    properties: {
        dry_run: {
            type: 'boolean',
            title: 'Dry Run'
        },
        groups: {
            items: {
                '$ref': '#/components/schemas/DeduplicateMerge'
            },
            type: 'array',
            title: 'Groups'
        },
        removed_count: {
            type: 'integer',
            title: 'Removed Count'
        }
    },
    type: 'object',
    required: ['dry_run', 'groups', 'removed_count'],
    title: 'DeduplicateResponse'
} as const;

export const DifficultySchema = {
    type: 'string',
    enum: ['easy', 'medium', 'hard'],
    title: 'Difficulty'
} as const;

export const EstimatePricesRequestSchema = {
    properties: {
        ingredient_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Ingredient Ids',
            default: []
        },
        currency: {
            type: 'string',
            title: 'Currency',
            default: 'EUR'
        }
    },
    type: 'object',
    title: 'EstimatePricesRequest',
    description: `Which ingredients to price, and in what currency.

An empty \`\`ingredient_ids\`\` means "everything without a curated price",
which is the common case after a bulk import.`
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ImportSourceSchema = {
    type: 'string',
    enum: ['url', 'photo'],
    title: 'ImportSource',
    description: 'How a recipe entered the app, when it was not typed in by hand.'
} as const;

export const ImportUrlRequestSchema = {
    properties: {
        url: {
            type: 'string',
            maxLength: 2083,
            minLength: 1,
            format: 'uri',
            title: 'Url'
        },
        language: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Language'
        }
    },
    type: 'object',
    required: ['url'],
    title: 'ImportUrlRequest'
} as const;

export const IngredientCategorySchema = {
    type: 'string',
    enum: ['produce', 'dairy', 'meat', 'seafood', 'grains', 'pantry', 'spices', 'beverages', 'frozen', 'bakery', 'other'],
    title: 'IngredientCategory'
} as const;

export const IngredientCreateSchema = {
    properties: {
        price_amount: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*(?:\\d{0,6}|(?=[\\d.]{1,11}0*$)\\d{0,6}\\.\\d{0,4}0*$)'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Amount'
        },
        price_quantity: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Quantity'
        },
        price_unit: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Unit'
                },
                {
                    type: 'null'
                }
            ]
        },
        density_g_per_ml: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Density G Per Ml'
        },
        piece_weight_g: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Piece Weight G'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        category: {
            '$ref': '#/components/schemas/IngredientCategory',
            default: 'other'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'IngredientCreate'
} as const;

export const IngredientPriceCreateSchema = {
    properties: {
        price_amount: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*(?:\\d{0,6}|(?=[\\d.]{1,11}0*$)\\d{0,6}\\.\\d{0,4}0*$)'
                }
            ],
            title: 'Price Amount'
        },
        price_quantity: {
            type: 'number',
            exclusiveMinimum: 0,
            title: 'Price Quantity'
        },
        price_unit: {
            '$ref': '#/components/schemas/Unit'
        },
        store_id: {
            type: 'string',
            format: 'uuid',
            title: 'Store Id'
        }
    },
    type: 'object',
    required: ['price_amount', 'price_quantity', 'price_unit', 'store_id'],
    title: 'IngredientPriceCreate'
} as const;

export const IngredientPricePublicSchema = {
    properties: {
        price_amount: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*(?:\\d{0,6}|(?=[\\d.]{1,11}0*$)\\d{0,6}\\.\\d{0,4}0*$)',
            title: 'Price Amount'
        },
        price_quantity: {
            type: 'number',
            exclusiveMinimum: 0,
            title: 'Price Quantity'
        },
        price_unit: {
            '$ref': '#/components/schemas/Unit'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        ingredient_id: {
            type: 'string',
            format: 'uuid',
            title: 'Ingredient Id'
        },
        store_id: {
            type: 'string',
            format: 'uuid',
            title: 'Store Id'
        },
        store_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Store Name'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['price_amount', 'price_quantity', 'price_unit', 'id', 'ingredient_id', 'store_id'],
    title: 'IngredientPricePublic'
} as const;

export const IngredientPricesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/IngredientPricePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'IngredientPricesPublic'
} as const;

export const IngredientPublicSchema = {
    properties: {
        price_amount: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*(?:\\d{0,6}|(?=[\\d.]{1,11}0*$)\\d{0,6}\\.\\d{0,4}0*$)'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Amount'
        },
        price_quantity: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Quantity'
        },
        price_unit: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Unit'
                },
                {
                    type: 'null'
                }
            ]
        },
        density_g_per_ml: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Density G Per Ml'
        },
        piece_weight_g: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Piece Weight G'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        name_en: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name En'
        },
        category: {
            '$ref': '#/components/schemas/IngredientCategory'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        price_source: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PriceSource'
                },
                {
                    type: 'null'
                }
            ]
        },
        price_updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Updated At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'name_en', 'category', 'image_url'],
    title: 'IngredientPublic'
} as const;

export const IngredientUpdateSchema = {
    properties: {
        price_amount: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*(?:\\d{0,6}|(?=[\\d.]{1,11}0*$)\\d{0,6}\\.\\d{0,4}0*$)'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Amount'
        },
        price_quantity: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Quantity'
        },
        price_unit: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Unit'
                },
                {
                    type: 'null'
                }
            ]
        },
        density_g_per_ml: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Density G Per Ml'
        },
        piece_weight_g: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Piece Weight G'
        },
        category: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/IngredientCategory'
                },
                {
                    type: 'null'
                }
            ]
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        }
    },
    type: 'object',
    title: 'IngredientUpdate'
} as const;

export const IngredientsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/IngredientPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'IngredientsPublic'
} as const;

export const MealTypeSchema = {
    type: 'string',
    enum: ['breakfast', 'lunch', 'dinner', 'snack', 'dessert', 'drink', 'other'],
    title: 'MealType'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const ParsedIngredientSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        name_en: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name En'
        },
        quantity: {
            type: 'number',
            title: 'Quantity'
        },
        unit: {
            '$ref': '#/components/schemas/Unit'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        category: {
            '$ref': '#/components/schemas/IngredientCategory',
            default: 'other'
        }
    },
    type: 'object',
    required: ['name', 'quantity', 'unit'],
    title: 'ParsedIngredient'
} as const;

export const ParsedRecipeSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        steps: {
            items: {
                '$ref': '#/components/schemas/ParsedStep'
            },
            type: 'array',
            title: 'Steps',
            default: []
        },
        servings: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Servings'
        },
        prep_time_minutes: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Prep Time Minutes'
        },
        cook_time_minutes: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cook Time Minutes'
        },
        ingredients: {
            items: {
                '$ref': '#/components/schemas/ParsedIngredient'
            },
            type: 'array',
            title: 'Ingredients',
            default: []
        },
        source_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Url'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        seasons: {
            items: {
                '$ref': '#/components/schemas/Season'
            },
            type: 'array',
            title: 'Seasons',
            default: []
        },
        is_vegan: {
            type: 'boolean',
            title: 'Is Vegan',
            default: false
        },
        is_vegetarian: {
            type: 'boolean',
            title: 'Is Vegetarian',
            default: false
        },
        is_gluten_free: {
            type: 'boolean',
            title: 'Is Gluten Free',
            default: false
        },
        is_dairy_free: {
            type: 'boolean',
            title: 'Is Dairy Free',
            default: false
        },
        kcal_per_serving: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Kcal Per Serving'
        },
        difficulty: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Difficulty'
                },
                {
                    type: 'null'
                }
            ]
        },
        meal_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MealType'
                },
                {
                    type: 'null'
                }
            ]
        },
        cuisine_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cuisine Type'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ParsedRecipe'
} as const;

export const ParsedStepSchema = {
    properties: {
        instruction: {
            type: 'string',
            title: 'Instruction'
        },
        ingredient_names: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Ingredient Names',
            default: []
        }
    },
    type: 'object',
    required: ['instruction'],
    title: 'ParsedStep'
} as const;

export const PriceSourceSchema = {
    type: 'string',
    enum: ['manual', 'estimated'],
    title: 'PriceSource',
    description: `Where an ingredient's reference price came from.

\`\`ESTIMATED\`\` rows were filled in by the LLM assist and may be overwritten
by a later estimate run; \`\`MANUAL\`\` rows were curated by a human and never
are.`
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const RecipeCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        servings: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Servings'
        },
        prep_time_minutes: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Prep Time Minutes'
        },
        cook_time_minutes: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cook Time Minutes'
        },
        source_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Url'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        is_public: {
            type: 'boolean',
            title: 'Is Public',
            default: false
        },
        seasons: {
            items: {
                '$ref': '#/components/schemas/Season'
            },
            type: 'array',
            title: 'Seasons'
        },
        is_vegan: {
            type: 'boolean',
            title: 'Is Vegan',
            default: false
        },
        is_vegetarian: {
            type: 'boolean',
            title: 'Is Vegetarian',
            default: false
        },
        is_gluten_free: {
            type: 'boolean',
            title: 'Is Gluten Free',
            default: false
        },
        is_dairy_free: {
            type: 'boolean',
            title: 'Is Dairy Free',
            default: false
        },
        kcal_per_serving: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Kcal Per Serving'
        },
        difficulty: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Difficulty'
                },
                {
                    type: 'null'
                }
            ]
        },
        meal_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MealType'
                },
                {
                    type: 'null'
                }
            ]
        },
        cuisine_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cuisine Type'
        },
        ingredients: {
            items: {
                '$ref': '#/components/schemas/RecipeIngredientCreate'
            },
            type: 'array',
            title: 'Ingredients',
            default: []
        },
        steps: {
            items: {
                '$ref': '#/components/schemas/RecipeStepCreate'
            },
            type: 'array',
            title: 'Steps',
            default: []
        },
        import_consent: {
            type: 'boolean',
            title: 'Import Consent',
            default: false
        },
        import_source: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ImportSource'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['title'],
    title: 'RecipeCreate'
} as const;

export const RecipeIngredientCreateSchema = {
    properties: {
        ingredient_name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Ingredient Name'
        },
        quantity: {
            type: 'number',
            exclusiveMinimum: 0,
            title: 'Quantity'
        },
        unit: {
            '$ref': '#/components/schemas/Unit'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        category: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/IngredientCategory'
                },
                {
                    type: 'null'
                }
            ]
        },
        name_en: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name En'
        }
    },
    type: 'object',
    required: ['ingredient_name', 'quantity', 'unit'],
    title: 'RecipeIngredientCreate'
} as const;

export const RecipeIngredientPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        ingredient_name: {
            type: 'string',
            title: 'Ingredient Name'
        },
        quantity: {
            type: 'number',
            title: 'Quantity'
        },
        unit: {
            '$ref': '#/components/schemas/Unit'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        estimated_cost: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Estimated Cost'
        }
    },
    type: 'object',
    required: ['id', 'ingredient_name', 'quantity', 'unit'],
    title: 'RecipeIngredientPublic'
} as const;

export const RecipePublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        servings: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Servings'
        },
        prep_time_minutes: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Prep Time Minutes'
        },
        cook_time_minutes: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cook Time Minutes'
        },
        source_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Url'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        is_public: {
            type: 'boolean',
            title: 'Is Public',
            default: false
        },
        seasons: {
            items: {
                '$ref': '#/components/schemas/Season'
            },
            type: 'array',
            title: 'Seasons'
        },
        is_vegan: {
            type: 'boolean',
            title: 'Is Vegan',
            default: false
        },
        is_vegetarian: {
            type: 'boolean',
            title: 'Is Vegetarian',
            default: false
        },
        is_gluten_free: {
            type: 'boolean',
            title: 'Is Gluten Free',
            default: false
        },
        is_dairy_free: {
            type: 'boolean',
            title: 'Is Dairy Free',
            default: false
        },
        kcal_per_serving: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Kcal Per Serving'
        },
        difficulty: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Difficulty'
                },
                {
                    type: 'null'
                }
            ]
        },
        meal_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MealType'
                },
                {
                    type: 'null'
                }
            ]
        },
        cuisine_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cuisine Type'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        owner_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner Name'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        ingredients: {
            items: {
                '$ref': '#/components/schemas/RecipeIngredientPublic'
            },
            type: 'array',
            title: 'Ingredients',
            default: []
        },
        steps: {
            items: {
                '$ref': '#/components/schemas/RecipeStepPublic'
            },
            type: 'array',
            title: 'Steps',
            default: []
        },
        estimated_cost: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Estimated Cost'
        },
        estimated_cost_per_serving: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Estimated Cost Per Serving'
        },
        unpriced_ingredient_count: {
            type: 'integer',
            title: 'Unpriced Ingredient Count',
            default: 0
        },
        currency: {
            type: 'string',
            title: 'Currency',
            default: 'EUR'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'RecipePublic'
} as const;

export const RecipeStepCreateSchema = {
    properties: {
        step_number: {
            type: 'integer',
            title: 'Step Number'
        },
        instruction: {
            type: 'string',
            minLength: 1,
            title: 'Instruction'
        },
        ingredient_indices: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Ingredient Indices',
            default: []
        }
    },
    type: 'object',
    required: ['step_number', 'instruction'],
    title: 'RecipeStepCreate'
} as const;

export const RecipeStepIngredientPublicSchema = {
    properties: {
        recipe_ingredient_id: {
            type: 'string',
            format: 'uuid',
            title: 'Recipe Ingredient Id'
        },
        ingredient_name: {
            type: 'string',
            title: 'Ingredient Name'
        }
    },
    type: 'object',
    required: ['recipe_ingredient_id', 'ingredient_name'],
    title: 'RecipeStepIngredientPublic'
} as const;

export const RecipeStepPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        step_number: {
            type: 'integer',
            title: 'Step Number'
        },
        instruction: {
            type: 'string',
            title: 'Instruction'
        },
        ingredients: {
            items: {
                '$ref': '#/components/schemas/RecipeStepIngredientPublic'
            },
            type: 'array',
            title: 'Ingredients',
            default: []
        }
    },
    type: 'object',
    required: ['id', 'step_number', 'instruction'],
    title: 'RecipeStepPublic'
} as const;

export const RecipeUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        servings: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Servings'
        },
        prep_time_minutes: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Prep Time Minutes'
        },
        cook_time_minutes: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cook Time Minutes'
        },
        source_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Url'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        is_public: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Public'
        },
        ingredients: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/RecipeIngredientCreate'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ingredients'
        },
        steps: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/RecipeStepCreate'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Steps'
        },
        seasons: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/Season'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Seasons'
        },
        is_vegan: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Vegan'
        },
        is_vegetarian: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Vegetarian'
        },
        is_gluten_free: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Gluten Free'
        },
        is_dairy_free: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Dairy Free'
        },
        kcal_per_serving: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Kcal Per Serving'
        },
        difficulty: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Difficulty'
                },
                {
                    type: 'null'
                }
            ]
        },
        meal_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MealType'
                },
                {
                    type: 'null'
                }
            ]
        },
        cuisine_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cuisine Type'
        }
    },
    type: 'object',
    title: 'RecipeUpdate'
} as const;

export const RecipesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RecipePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RecipesPublic'
} as const;

export const ReimportRequestSchema = {
    properties: {
        language: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Language'
        }
    },
    type: 'object',
    title: 'ReimportRequest'
} as const;

export const SeasonSchema = {
    type: 'string',
    enum: ['spring', 'summer', 'autumn', 'winter'],
    title: 'Season'
} as const;

export const ShoppingFrequencySchema = {
    type: 'string',
    enum: ['weekly', 'biweekly', 'monthly'],
    title: 'ShoppingFrequency'
} as const;

export const ShoppingListCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ShoppingListCreate'
} as const;

export const ShoppingListItemCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        quantity: {
            type: 'number',
            exclusiveMinimum: 0,
            title: 'Quantity'
        },
        unit: {
            '$ref': '#/components/schemas/Unit'
        },
        is_checked: {
            type: 'boolean',
            title: 'Is Checked',
            default: false
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: ['name', 'quantity', 'unit'],
    title: 'ShoppingListItemCreate'
} as const;

export const ShoppingListItemPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        quantity: {
            type: 'number',
            title: 'Quantity'
        },
        unit: {
            '$ref': '#/components/schemas/Unit'
        },
        is_checked: {
            type: 'boolean',
            title: 'Is Checked'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        estimated_cost: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Estimated Cost'
        }
    },
    type: 'object',
    required: ['id', 'name', 'quantity', 'unit', 'is_checked'],
    title: 'ShoppingListItemPublic'
} as const;

export const ShoppingListItemUpdateSchema = {
    properties: {
        quantity: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quantity'
        },
        unit: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Unit'
                },
                {
                    type: 'null'
                }
            ]
        },
        is_checked: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Checked'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'ShoppingListItemUpdate'
} as const;

export const ShoppingListPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/ShoppingListItemPublic'
            },
            type: 'array',
            title: 'Items',
            default: []
        },
        planned_recipes: {
            items: {
                '$ref': '#/components/schemas/ShoppingListRecipePublic'
            },
            type: 'array',
            title: 'Planned Recipes',
            default: []
        },
        estimated_total: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Estimated Total'
        },
        unpriced_item_count: {
            type: 'integer',
            title: 'Unpriced Item Count',
            default: 0
        },
        currency: {
            type: 'string',
            title: 'Currency',
            default: 'EUR'
        }
    },
    type: 'object',
    required: ['name', 'id', 'owner_id'],
    title: 'ShoppingListPublic'
} as const;

export const ShoppingListRecipePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        recipe_id: {
            type: 'string',
            format: 'uuid',
            title: 'Recipe Id'
        },
        recipe_title: {
            type: 'string',
            title: 'Recipe Title'
        },
        recipe_servings: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recipe Servings'
        },
        servings_planned: {
            type: 'integer',
            title: 'Servings Planned'
        },
        is_prepared: {
            type: 'boolean',
            title: 'Is Prepared'
        },
        ingredients: {
            items: {
                '$ref': '#/components/schemas/RecipeIngredientPublic'
            },
            type: 'array',
            title: 'Ingredients',
            default: []
        },
        estimated_cost: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Estimated Cost'
        }
    },
    type: 'object',
    required: ['id', 'recipe_id', 'recipe_title', 'recipe_servings', 'servings_planned', 'is_prepared'],
    title: 'ShoppingListRecipePublic'
} as const;

export const ShoppingListRecipeUpdateSchema = {
    properties: {
        is_prepared: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Prepared'
        },
        servings_planned: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Servings Planned'
        }
    },
    type: 'object',
    title: 'ShoppingListRecipeUpdate'
} as const;

export const ShoppingListUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        }
    },
    type: 'object',
    title: 'ShoppingListUpdate'
} as const;

export const ShoppingListsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ShoppingListPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ShoppingListsPublic'
} as const;

export const StoreComparisonSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/StoreComparisonEntry'
            },
            type: 'array',
            title: 'Data'
        },
        cheapest_store_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cheapest Store Id'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'StoreComparison'
} as const;

export const StoreComparisonEntrySchema = {
    properties: {
        store_id: {
            type: 'string',
            format: 'uuid',
            title: 'Store Id'
        },
        store_name: {
            type: 'string',
            title: 'Store Name'
        },
        store_slug: {
            type: 'string',
            title: 'Store Slug'
        },
        currency: {
            type: 'string',
            title: 'Currency'
        },
        estimated_total: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Estimated Total'
        },
        unpriced_item_count: {
            type: 'integer',
            title: 'Unpriced Item Count',
            default: 0
        }
    },
    type: 'object',
    required: ['store_id', 'store_name', 'store_slug', 'currency'],
    title: 'StoreComparisonEntry',
    description: 'What one shopping list would cost at one store.'
} as const;

export const StoreCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        slug: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Slug'
        },
        country: {
            type: 'string',
            maxLength: 2,
            minLength: 2,
            title: 'Country',
            default: 'FR'
        },
        currency: {
            type: 'string',
            maxLength: 3,
            minLength: 3,
            title: 'Currency',
            default: 'EUR'
        },
        price_index: {
            type: 'number',
            exclusiveMinimum: 0,
            title: 'Price Index',
            default: 1
        },
        logo_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Logo Url'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['name', 'slug'],
    title: 'StoreCreate'
} as const;

export const StorePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        slug: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Slug'
        },
        country: {
            type: 'string',
            maxLength: 2,
            minLength: 2,
            title: 'Country',
            default: 'FR'
        },
        currency: {
            type: 'string',
            maxLength: 3,
            minLength: 3,
            title: 'Currency',
            default: 'EUR'
        },
        price_index: {
            type: 'number',
            exclusiveMinimum: 0,
            title: 'Price Index',
            default: 1
        },
        logo_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Logo Url'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'slug', 'id'],
    title: 'StorePublic'
} as const;

export const StoreUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2,
                    minLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 3,
                    minLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Currency'
        },
        price_index: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Index'
        },
        logo_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Logo Url'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'StoreUpdate'
} as const;

export const StoresPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/StorePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'StoresPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UnitSchema = {
    type: 'string',
    enum: ['g', 'kg', 'ml', 'cl', 'dl', 'L', 'piece', 'tbsp', 'tsp', 'cup', 'oz', 'lb', 'bunch', 'pinch', 'clove', 'slice', 'can', 'package'],
    title: 'Unit'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserSettingsPublicSchema = {
    properties: {
        household_size: {
            type: 'integer',
            minimum: 1,
            title: 'Household Size',
            default: 2
        },
        shopping_frequency: {
            '$ref': '#/components/schemas/ShoppingFrequency',
            default: 'weekly'
        },
        budget_amount: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*(?:\\d{0,8}|(?=[\\d.]{1,11}0*$)\\d{0,8}\\.\\d{0,2}0*$)'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Budget Amount'
        },
        currency: {
            type: 'string',
            maxLength: 3,
            minLength: 3,
            title: 'Currency',
            default: 'EUR'
        },
        preferred_store_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preferred Store Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        }
    },
    type: 'object',
    required: ['id', 'user_id'],
    title: 'UserSettingsPublic'
} as const;

export const UserSettingsUpdateSchema = {
    properties: {
        household_size: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Household Size'
        },
        shopping_frequency: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ShoppingFrequency'
                },
                {
                    type: 'null'
                }
            ]
        },
        budget_amount: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*(?:\\d{0,8}|(?=[\\d.]{1,11}0*$)\\d{0,8}\\.\\d{0,2}0*$)'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Budget Amount'
        },
        currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 3,
                    minLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Currency'
        },
        preferred_store_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preferred Store Id'
        }
    },
    type: 'object',
    title: 'UserSettingsUpdate'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;