// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type {
    ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse,
    LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse,
    PrivateCreateUserData, PrivateCreateUserResponse,
    UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse,
    UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse,
    HouseholdsReadHouseholdsResponse, HouseholdsReadHouseholdData, HouseholdsReadHouseholdResponse, HouseholdsCreateHouseholdData, HouseholdsCreateHouseholdResponse, HouseholdsUpdateHouseholdData, HouseholdsUpdateHouseholdResponse, HouseholdsDeleteHouseholdData, HouseholdsDeleteHouseholdResponse, HouseholdsAddMemberData, HouseholdsAddMemberResponse, HouseholdsRemoveMemberData, HouseholdsRemoveMemberResponse,
    RecipesReadRecipesData, RecipesReadRecipesResponse, RecipesReadRecipeData, RecipesReadRecipeResponse, RecipesCreateRecipeData, RecipesCreateRecipeResponse, RecipesUpdateRecipeData, RecipesUpdateRecipeResponse, RecipesDeleteRecipeData, RecipesDeleteRecipeResponse, RecipesAddIngredientData, RecipesAddIngredientResponse, RecipesUpdateIngredientData, RecipesUpdateIngredientResponse, RecipesDeleteIngredientData, RecipesDeleteIngredientResponse,
    ShoppingListsReadListsResponse, ShoppingListsReadListData, ShoppingListsReadListResponse, ShoppingListsCreateListData, ShoppingListsCreateListResponse, ShoppingListsUpdateListData, ShoppingListsUpdateListResponse, ShoppingListsDeleteListData, ShoppingListsDeleteListResponse, ShoppingListsAddRecipeData, ShoppingListsAddRecipeResponse, ShoppingListsUpdateRecipeData, ShoppingListsUpdateRecipeResponse, ShoppingListsRemoveRecipeData, ShoppingListsRemoveRecipeResponse, ShoppingListsToggleIngredientData, ShoppingListsToggleIngredientResponse,
} from './types.gen';

export class ItemsService {
    /**
     * Read Items
     * Retrieve items.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Item
     * Create new item.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Item
     * Get item by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Item
     * Update an item.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Item
     * Delete an item.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}

export class HouseholdsService {
    public static readHouseholds(): CancelablePromise<HouseholdsReadHouseholdsResponse> {
        return __request(OpenAPI, { method: 'GET', url: '/api/v1/households/' });
    }
    public static readHousehold(data: HouseholdsReadHouseholdData): CancelablePromise<HouseholdsReadHouseholdResponse> {
        return __request(OpenAPI, { method: 'GET', url: '/api/v1/households/{id}', path: { id: data.id } });
    }
    public static createHousehold(data: HouseholdsCreateHouseholdData): CancelablePromise<HouseholdsCreateHouseholdResponse> {
        return __request(OpenAPI, { method: 'POST', url: '/api/v1/households/', body: data.requestBody, mediaType: 'application/json' });
    }
    public static updateHousehold(data: HouseholdsUpdateHouseholdData): CancelablePromise<HouseholdsUpdateHouseholdResponse> {
        return __request(OpenAPI, { method: 'PUT', url: '/api/v1/households/{id}', path: { id: data.id }, body: data.requestBody, mediaType: 'application/json' });
    }
    public static deleteHousehold(data: HouseholdsDeleteHouseholdData): CancelablePromise<HouseholdsDeleteHouseholdResponse> {
        return __request(OpenAPI, { method: 'DELETE', url: '/api/v1/households/{id}', path: { id: data.id } });
    }
    public static addMember(data: HouseholdsAddMemberData): CancelablePromise<HouseholdsAddMemberResponse> {
        return __request(OpenAPI, { method: 'POST', url: '/api/v1/households/{id}/members', path: { id: data.id }, query: { user_email: data.userEmail } });
    }
    public static removeMember(data: HouseholdsRemoveMemberData): CancelablePromise<HouseholdsRemoveMemberResponse> {
        return __request(OpenAPI, { method: 'DELETE', url: '/api/v1/households/{id}/members/{user_id}', path: { id: data.id, user_id: data.userId } });
    }
}

export class RecipesService {
    public static readRecipes(data: RecipesReadRecipesData = {}): CancelablePromise<RecipesReadRecipesResponse> {
        return __request(OpenAPI, { method: 'GET', url: '/api/v1/recipes/', query: { skip: data.skip, limit: data.limit } });
    }
    public static readRecipe(data: RecipesReadRecipeData): CancelablePromise<RecipesReadRecipeResponse> {
        return __request(OpenAPI, { method: 'GET', url: '/api/v1/recipes/{id}', path: { id: data.id } });
    }
    public static createRecipe(data: RecipesCreateRecipeData): CancelablePromise<RecipesCreateRecipeResponse> {
        return __request(OpenAPI, { method: 'POST', url: '/api/v1/recipes/', body: data.requestBody, mediaType: 'application/json' });
    }
    public static updateRecipe(data: RecipesUpdateRecipeData): CancelablePromise<RecipesUpdateRecipeResponse> {
        return __request(OpenAPI, { method: 'PUT', url: '/api/v1/recipes/{id}', path: { id: data.id }, body: data.requestBody, mediaType: 'application/json' });
    }
    public static deleteRecipe(data: RecipesDeleteRecipeData): CancelablePromise<RecipesDeleteRecipeResponse> {
        return __request(OpenAPI, { method: 'DELETE', url: '/api/v1/recipes/{id}', path: { id: data.id } });
    }
    public static addIngredient(data: RecipesAddIngredientData): CancelablePromise<RecipesAddIngredientResponse> {
        return __request(OpenAPI, { method: 'POST', url: '/api/v1/recipes/{id}/ingredients', path: { id: data.id }, body: data.requestBody, mediaType: 'application/json' });
    }
    public static updateIngredient(data: RecipesUpdateIngredientData): CancelablePromise<RecipesUpdateIngredientResponse> {
        return __request(OpenAPI, { method: 'PUT', url: '/api/v1/recipes/{id}/ingredients/{ingredient_id}', path: { id: data.id, ingredient_id: data.ingredientId }, body: data.requestBody, mediaType: 'application/json' });
    }
    public static deleteIngredient(data: RecipesDeleteIngredientData): CancelablePromise<RecipesDeleteIngredientResponse> {
        return __request(OpenAPI, { method: 'DELETE', url: '/api/v1/recipes/{id}/ingredients/{ingredient_id}', path: { id: data.id, ingredient_id: data.ingredientId } });
    }
}

export class ShoppingListsService {
    public static readShoppingLists(): CancelablePromise<ShoppingListsReadListsResponse> {
        return __request(OpenAPI, { method: 'GET', url: '/api/v1/shopping-lists/' });
    }
    public static readShoppingList(data: ShoppingListsReadListData): CancelablePromise<ShoppingListsReadListResponse> {
        return __request(OpenAPI, { method: 'GET', url: '/api/v1/shopping-lists/{id}', path: { id: data.id } });
    }
    public static createShoppingList(data: ShoppingListsCreateListData): CancelablePromise<ShoppingListsCreateListResponse> {
        return __request(OpenAPI, { method: 'POST', url: '/api/v1/shopping-lists/', body: data.requestBody, mediaType: 'application/json' });
    }
    public static updateShoppingList(data: ShoppingListsUpdateListData): CancelablePromise<ShoppingListsUpdateListResponse> {
        return __request(OpenAPI, { method: 'PUT', url: '/api/v1/shopping-lists/{id}', path: { id: data.id }, body: data.requestBody, mediaType: 'application/json' });
    }
    public static deleteShoppingList(data: ShoppingListsDeleteListData): CancelablePromise<ShoppingListsDeleteListResponse> {
        return __request(OpenAPI, { method: 'DELETE', url: '/api/v1/shopping-lists/{id}', path: { id: data.id } });
    }
    public static addRecipe(data: ShoppingListsAddRecipeData): CancelablePromise<ShoppingListsAddRecipeResponse> {
        return __request(OpenAPI, { method: 'POST', url: '/api/v1/shopping-lists/{id}/recipes', path: { id: data.id }, body: data.requestBody, mediaType: 'application/json' });
    }
    public static updateRecipe(data: ShoppingListsUpdateRecipeData): CancelablePromise<ShoppingListsUpdateRecipeResponse> {
        return __request(OpenAPI, { method: 'PUT', url: '/api/v1/shopping-lists/{id}/recipes/{entry_id}', path: { id: data.id, entry_id: data.entryId }, body: data.requestBody, mediaType: 'application/json' });
    }
    public static removeRecipe(data: ShoppingListsRemoveRecipeData): CancelablePromise<ShoppingListsRemoveRecipeResponse> {
        return __request(OpenAPI, { method: 'DELETE', url: '/api/v1/shopping-lists/{id}/recipes/{entry_id}', path: { id: data.id, entry_id: data.entryId } });
    }
    public static toggleIngredient(data: ShoppingListsToggleIngredientData): CancelablePromise<ShoppingListsToggleIngredientResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/shopping-lists/{id}/ingredients/check',
            path: { id: data.id },
            query: { ingredient_name: data.ingredient_name, unit: data.unit, is_checked: data.is_checked }
        });
    }
}