// This file is auto-generated by @hey-api/openapi-ts

/**
 * An ingredient aggregated across all recipes in a shopping list.
 */
export type AggregatedIngredient = {
    name: string;
    unit: string;
    total_quantity: number;
    is_checked: boolean;
    sources: Array<{
        [key: string]: unknown;
    }>;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HouseholdCreate = {
    name: string;
};

export type HouseholdMemberPublic = {
    user_id: string;
    user_email: string;
    user_full_name?: (string | null);
};

export type HouseholdPublic = {
    name: string;
    id: string;
    owner_id: string;
    created_at?: (string | null);
    members?: Array<HouseholdMemberPublic>;
    member_count?: number;
};

export type HouseholdsPublic = {
    data: Array<HouseholdPublic>;
    count: number;
};

export type HouseholdUpdate = {
    name?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RecipeCreate = {
    title: string;
    description?: (string | null);
    base_servings?: number;
    ingredients?: Array<RecipeIngredientCreate>;
};

export type RecipeIngredientCreate = {
    name: string;
    quantity: number;
    unit: string;
};

export type RecipeIngredientPublic = {
    name: string;
    quantity: number;
    unit: string;
    id: string;
    recipe_id: string;
};

export type RecipeIngredientUpdate = {
    name?: (string | null);
    quantity?: (number | null);
    unit?: (string | null);
};

export type RecipePublic = {
    title: string;
    description?: (string | null);
    base_servings?: number;
    id: string;
    owner_id: string;
    created_at?: (string | null);
    ingredients?: Array<RecipeIngredientPublic>;
};

export type RecipesPublic = {
    data: Array<RecipePublic>;
    count: number;
};

export type RecipeUpdate = {
    title?: (string | null);
    description?: (string | null);
    base_servings?: (number | null);
    ingredients?: (Array<RecipeIngredientCreate> | null);
};

export type ShoppingListCreate = {
    name: string;
};

export type ShoppingListPublic = {
    name: string;
    id: string;
    owner_id: string;
    created_at?: (string | null);
    recipes?: Array<ShoppingListRecipePublic>;
    ingredients?: Array<AggregatedIngredient>;
};

export type ShoppingListRecipeCreate = {
    num_people: number;
    num_meals?: number;
    recipe_id: string;
};

export type ShoppingListRecipePublic = {
    num_people: number;
    num_meals?: number;
    id: string;
    recipe_id: string;
    recipe_title: string;
    recipe_base_servings: number;
};

export type ShoppingListRecipeUpdate = {
    num_people?: (number | null);
    num_meals?: (number | null);
};

export type ShoppingListsSummary = {
    data: Array<ShoppingListSummary>;
    count: number;
};

export type ShoppingListSummary = {
    name: string;
    id: string;
    owner_id: string;
    created_at?: (string | null);
    recipe_count?: number;
};

export type ShoppingListUpdate = {
    name?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type HouseholdsReadHouseholdsResponse = (HouseholdsPublic);

export type HouseholdsCreateHouseholdData = {
    requestBody: HouseholdCreate;
};

export type HouseholdsCreateHouseholdResponse = (HouseholdPublic);

export type HouseholdsReadHouseholdData = {
    id: string;
};

export type HouseholdsReadHouseholdResponse = (HouseholdPublic);

export type HouseholdsUpdateHouseholdData = {
    id: string;
    requestBody: HouseholdUpdate;
};

export type HouseholdsUpdateHouseholdResponse = (HouseholdPublic);

export type HouseholdsDeleteHouseholdData = {
    id: string;
};

export type HouseholdsDeleteHouseholdResponse = (Message);

export type HouseholdsAddMemberData = {
    id: string;
    userEmail: string;
};

export type HouseholdsAddMemberResponse = (HouseholdPublic);

export type HouseholdsRemoveMemberData = {
    id: string;
    userId: string;
};

export type HouseholdsRemoveMemberResponse = (HouseholdPublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RecipesReadRecipesData = {
    limit?: number;
    skip?: number;
};

export type RecipesReadRecipesResponse = (RecipesPublic);

export type RecipesCreateRecipeData = {
    requestBody: RecipeCreate;
};

export type RecipesCreateRecipeResponse = (RecipePublic);

export type RecipesReadRecipeData = {
    id: string;
};

export type RecipesReadRecipeResponse = (RecipePublic);

export type RecipesUpdateRecipeData = {
    id: string;
    requestBody: RecipeUpdate;
};

export type RecipesUpdateRecipeResponse = (RecipePublic);

export type RecipesDeleteRecipeData = {
    id: string;
};

export type RecipesDeleteRecipeResponse = (Message);

export type RecipesAddIngredientData = {
    id: string;
    requestBody: RecipeIngredientCreate;
};

export type RecipesAddIngredientResponse = (RecipeIngredientPublic);

export type RecipesUpdateIngredientData = {
    id: string;
    ingredientId: string;
    requestBody: RecipeIngredientUpdate;
};

export type RecipesUpdateIngredientResponse = (RecipeIngredientPublic);

export type RecipesDeleteIngredientData = {
    id: string;
    ingredientId: string;
};

export type RecipesDeleteIngredientResponse = (Message);

export type ShoppingListsReadShoppingListsData = {
    limit?: number;
    skip?: number;
};

export type ShoppingListsReadShoppingListsResponse = (ShoppingListsSummary);

export type ShoppingListsCreateShoppingListData = {
    requestBody: ShoppingListCreate;
};

export type ShoppingListsCreateShoppingListResponse = (ShoppingListPublic);

export type ShoppingListsReadShoppingListData = {
    id: string;
};

export type ShoppingListsReadShoppingListResponse = (ShoppingListPublic);

export type ShoppingListsUpdateShoppingListData = {
    id: string;
    requestBody: ShoppingListUpdate;
};

export type ShoppingListsUpdateShoppingListResponse = (ShoppingListPublic);

export type ShoppingListsDeleteShoppingListData = {
    id: string;
};

export type ShoppingListsDeleteShoppingListResponse = (Message);

export type ShoppingListsAddRecipeToListData = {
    id: string;
    requestBody: ShoppingListRecipeCreate;
};

export type ShoppingListsAddRecipeToListResponse = (ShoppingListPublic);

export type ShoppingListsUpdateRecipeInListData = {
    entryId: string;
    id: string;
    requestBody: ShoppingListRecipeUpdate;
};

export type ShoppingListsUpdateRecipeInListResponse = (ShoppingListPublic);

export type ShoppingListsRemoveRecipeFromListData = {
    entryId: string;
    id: string;
};

export type ShoppingListsRemoveRecipeFromListResponse = (ShoppingListPublic);

export type ShoppingListsToggleIngredientData = {
    id: string;
    ingredientName: string;
    isChecked: boolean;
    unit: string;
};

export type ShoppingListsToggleIngredientResponse = (ShoppingListPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);