"""drop redundant unique constraint on ingredient name

Revision ID: 4323ce51ce41
Revises: u3v4w5x6y7z8
Create Date: 2026-10-04 06:07:20.614240

`ingredient.name` carried two unique guards: the `ix_ingredient_name` unique
index the model declares (`unique=True, index=True`), and an
`ingredient_name_key` constraint an early migration left behind. Uniqueness is
still enforced by the index; this drops only the duplicate, which is what kept
`alembic check` from passing (see 373629b01b69, which recorded the drift).
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "4323ce51ce41"
down_revision = "u3v4w5x6y7z8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ingredient_name_key"), "ingredient", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("ingredient_name_key"),
        "ingredient",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
