"""add prices_refreshed_at to store

Revision ID: c7d8e9f0a1b2
Revises: 373629b01b69
Create Date: 2026-09-27 12:00:00.000000

Hand-written rather than autogenerated: autogenerate here still proposes the
unrelated enum and ``ingredient.name`` constraint rewrites described in
373629b01b69. This migration carries only the new column.
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c7d8e9f0a1b2"
down_revision = "373629b01b69"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        "store",
        sa.Column("prices_refreshed_at", sa.DateTime(timezone=True), nullable=True),
    )


def downgrade():
    op.drop_column("store", "prices_refreshed_at")
