"""track recipe import version

Revision ID: e663625767b7
Revises: 4323ce51ce41
Create Date: 2026-10-06 18:25:59.392446

``recipe.import_version`` records which revision of the import pipeline
(``recipe_import.IMPORT_VERSION``) last read a recipe from its URL. Existing
recipes keep ``NULL``: they predate the tracking, so the bulk reimport treats
every URL import among them as stale. ``recipe.reimport_attempted_at`` puts a
recipe a batch could not refresh at the back of the next one.

``recipe.import_language`` records the language a recipe was read in, so a
reimport reads it in the same one. Existing recipes keep ``NULL``: the bulk
reimport then falls back to the crawled site's language, or the admin's.
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "e663625767b7"
down_revision = "4323ce51ce41"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipe", sa.Column("import_version", sa.Integer(), nullable=True))
    op.add_column(
        "recipe",
        sa.Column(
            "import_language",
            sqlmodel.sql.sqltypes.AutoString(length=10),
            nullable=True,
        ),
    )
    op.add_column(
        "recipe",
        sa.Column("reimport_attempted_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipe", "reimport_attempted_at")
    op.drop_column("recipe", "import_language")
    op.drop_column("recipe", "import_version")
    # ### end Alembic commands ###
