/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutShoppingListsRouteImport } from './routes/_layout/shopping-lists'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutRecipesRouteImport } from './routes/_layout/recipes'
import { Route as LayoutIngredientsRouteImport } from './routes/_layout/ingredients'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutShoppingListsIdRouteImport } from './routes/_layout/shopping-lists.$id'
import { Route as LayoutRecipesIdRouteImport } from './routes/_layout/recipes.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutShoppingListsRoute = LayoutShoppingListsRouteImport.update({
  id: '/shopping-lists',
  path: '/shopping-lists',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRecipesRoute = LayoutRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutIngredientsRoute = LayoutIngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutShoppingListsIdRoute = LayoutShoppingListsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutShoppingListsRoute,
} as any)
const LayoutRecipesIdRoute = LayoutRecipesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutRecipesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/ingredients': typeof LayoutIngredientsRoute
  '/recipes': typeof LayoutRecipesRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/shopping-lists': typeof LayoutShoppingListsRouteWithChildren
  '/recipes/$id': typeof LayoutRecipesIdRoute
  '/shopping-lists/$id': typeof LayoutShoppingListsIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/ingredients': typeof LayoutIngredientsRoute
  '/recipes': typeof LayoutRecipesRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/shopping-lists': typeof LayoutShoppingListsRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/recipes/$id': typeof LayoutRecipesIdRoute
  '/shopping-lists/$id': typeof LayoutShoppingListsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/ingredients': typeof LayoutIngredientsRoute
  '/_layout/recipes': typeof LayoutRecipesRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/shopping-lists': typeof LayoutShoppingListsRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/recipes/$id': typeof LayoutRecipesIdRoute
  '/_layout/shopping-lists/$id': typeof LayoutShoppingListsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/ingredients'
    | '/recipes'
    | '/settings'
    | '/shopping-lists'
    | '/recipes/$id'
    | '/shopping-lists/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/ingredients'
    | '/recipes'
    | '/settings'
    | '/shopping-lists'
    | '/'
    | '/recipes/$id'
    | '/shopping-lists/$id'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/ingredients'
    | '/_layout/recipes'
    | '/_layout/settings'
    | '/_layout/shopping-lists'
    | '/_layout/'
    | '/_layout/recipes/$id'
    | '/_layout/shopping-lists/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/shopping-lists': {
      id: '/_layout/shopping-lists'
      path: '/shopping-lists'
      fullPath: '/shopping-lists'
      preLoaderRoute: typeof LayoutShoppingListsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/recipes': {
      id: '/_layout/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof LayoutRecipesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ingredients': {
      id: '/_layout/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof LayoutIngredientsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/shopping-lists/$id': {
      id: '/_layout/shopping-lists/$id'
      path: '/$id'
      fullPath: '/shopping-lists/$id'
      preLoaderRoute: typeof LayoutShoppingListsIdRouteImport
      parentRoute: typeof LayoutShoppingListsRoute
    }
    '/_layout/recipes/$id': {
      id: '/_layout/recipes/$id'
      path: '/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof LayoutRecipesIdRouteImport
      parentRoute: typeof LayoutRecipesRoute
    }
  }
}

interface LayoutRecipesRouteChildren {
  LayoutRecipesIdRoute: typeof LayoutRecipesIdRoute
}

const LayoutRecipesRouteChildren: LayoutRecipesRouteChildren = {
  LayoutRecipesIdRoute: LayoutRecipesIdRoute,
}

const LayoutRecipesRouteWithChildren = LayoutRecipesRoute._addFileChildren(
  LayoutRecipesRouteChildren,
)

interface LayoutShoppingListsRouteChildren {
  LayoutShoppingListsIdRoute: typeof LayoutShoppingListsIdRoute
}

const LayoutShoppingListsRouteChildren: LayoutShoppingListsRouteChildren = {
  LayoutShoppingListsIdRoute: LayoutShoppingListsIdRoute,
}

const LayoutShoppingListsRouteWithChildren =
  LayoutShoppingListsRoute._addFileChildren(LayoutShoppingListsRouteChildren)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutIngredientsRoute: typeof LayoutIngredientsRoute
  LayoutRecipesRoute: typeof LayoutRecipesRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutShoppingListsRoute: typeof LayoutShoppingListsRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutIngredientsRoute: LayoutIngredientsRoute,
  LayoutRecipesRoute: LayoutRecipesRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutShoppingListsRoute: LayoutShoppingListsRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
