/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutShareTargetRouteImport } from './routes/_layout/share-target'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutShoppingListsIndexRouteImport } from './routes/_layout/shopping-lists/index'
import { Route as LayoutRecipesIndexRouteImport } from './routes/_layout/recipes/index'
import { Route as LayoutAdminIndexRouteImport } from './routes/_layout/admin/index'
import { Route as LayoutShoppingListsIdRouteImport } from './routes/_layout/shopping-lists/$id'
import { Route as LayoutRecipesPublicRouteImport } from './routes/_layout/recipes/public'
import { Route as LayoutRecipesIdRouteImport } from './routes/_layout/recipes/$id'
import { Route as LayoutProfileUserIdRouteImport } from './routes/_layout/profile/$userId'
import { Route as LayoutAdminUsersRouteImport } from './routes/_layout/admin/users'
import { Route as LayoutAdminIngredientsRouteImport } from './routes/_layout/admin/ingredients'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutShareTargetRoute = LayoutShareTargetRouteImport.update({
  id: '/share-target',
  path: '/share-target',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutShoppingListsIndexRoute =
  LayoutShoppingListsIndexRouteImport.update({
    id: '/shopping-lists/',
    path: '/shopping-lists/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutRecipesIndexRoute = LayoutRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminIndexRoute = LayoutAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutShoppingListsIdRoute = LayoutShoppingListsIdRouteImport.update({
  id: '/shopping-lists/$id',
  path: '/shopping-lists/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRecipesPublicRoute = LayoutRecipesPublicRouteImport.update({
  id: '/recipes/public',
  path: '/recipes/public',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRecipesIdRoute = LayoutRecipesIdRouteImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileUserIdRoute = LayoutProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminUsersRoute = LayoutAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminIngredientsRoute = LayoutAdminIngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => LayoutAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/share-target': typeof LayoutShareTargetRoute
  '/admin/ingredients': typeof LayoutAdminIngredientsRoute
  '/admin/users': typeof LayoutAdminUsersRoute
  '/profile/$userId': typeof LayoutProfileUserIdRoute
  '/recipes/$id': typeof LayoutRecipesIdRoute
  '/recipes/public': typeof LayoutRecipesPublicRoute
  '/shopping-lists/$id': typeof LayoutShoppingListsIdRoute
  '/admin/': typeof LayoutAdminIndexRoute
  '/recipes/': typeof LayoutRecipesIndexRoute
  '/shopping-lists/': typeof LayoutShoppingListsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/settings': typeof LayoutSettingsRoute
  '/share-target': typeof LayoutShareTargetRoute
  '/': typeof LayoutIndexRoute
  '/admin/ingredients': typeof LayoutAdminIngredientsRoute
  '/admin/users': typeof LayoutAdminUsersRoute
  '/profile/$userId': typeof LayoutProfileUserIdRoute
  '/recipes/$id': typeof LayoutRecipesIdRoute
  '/recipes/public': typeof LayoutRecipesPublicRoute
  '/shopping-lists/$id': typeof LayoutShoppingListsIdRoute
  '/admin': typeof LayoutAdminIndexRoute
  '/recipes': typeof LayoutRecipesIndexRoute
  '/shopping-lists': typeof LayoutShoppingListsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/share-target': typeof LayoutShareTargetRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/ingredients': typeof LayoutAdminIngredientsRoute
  '/_layout/admin/users': typeof LayoutAdminUsersRoute
  '/_layout/profile/$userId': typeof LayoutProfileUserIdRoute
  '/_layout/recipes/$id': typeof LayoutRecipesIdRoute
  '/_layout/recipes/public': typeof LayoutRecipesPublicRoute
  '/_layout/shopping-lists/$id': typeof LayoutShoppingListsIdRoute
  '/_layout/admin/': typeof LayoutAdminIndexRoute
  '/_layout/recipes/': typeof LayoutRecipesIndexRoute
  '/_layout/shopping-lists/': typeof LayoutShoppingListsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/settings'
    | '/share-target'
    | '/admin/ingredients'
    | '/admin/users'
    | '/profile/$userId'
    | '/recipes/$id'
    | '/recipes/public'
    | '/shopping-lists/$id'
    | '/admin/'
    | '/recipes/'
    | '/shopping-lists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/settings'
    | '/share-target'
    | '/'
    | '/admin/ingredients'
    | '/admin/users'
    | '/profile/$userId'
    | '/recipes/$id'
    | '/recipes/public'
    | '/shopping-lists/$id'
    | '/admin'
    | '/recipes'
    | '/shopping-lists'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/settings'
    | '/_layout/share-target'
    | '/_layout/'
    | '/_layout/admin/ingredients'
    | '/_layout/admin/users'
    | '/_layout/profile/$userId'
    | '/_layout/recipes/$id'
    | '/_layout/recipes/public'
    | '/_layout/shopping-lists/$id'
    | '/_layout/admin/'
    | '/_layout/recipes/'
    | '/_layout/shopping-lists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/share-target': {
      id: '/_layout/share-target'
      path: '/share-target'
      fullPath: '/share-target'
      preLoaderRoute: typeof LayoutShareTargetRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/shopping-lists/': {
      id: '/_layout/shopping-lists/'
      path: '/shopping-lists'
      fullPath: '/shopping-lists/'
      preLoaderRoute: typeof LayoutShoppingListsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/recipes/': {
      id: '/_layout/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof LayoutRecipesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/': {
      id: '/_layout/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAdminIndexRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/shopping-lists/$id': {
      id: '/_layout/shopping-lists/$id'
      path: '/shopping-lists/$id'
      fullPath: '/shopping-lists/$id'
      preLoaderRoute: typeof LayoutShoppingListsIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/recipes/public': {
      id: '/_layout/recipes/public'
      path: '/recipes/public'
      fullPath: '/recipes/public'
      preLoaderRoute: typeof LayoutRecipesPublicRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/recipes/$id': {
      id: '/_layout/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof LayoutRecipesIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile/$userId': {
      id: '/_layout/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof LayoutProfileUserIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/users': {
      id: '/_layout/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof LayoutAdminUsersRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/ingredients': {
      id: '/_layout/admin/ingredients'
      path: '/ingredients'
      fullPath: '/admin/ingredients'
      preLoaderRoute: typeof LayoutAdminIngredientsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminIngredientsRoute: typeof LayoutAdminIngredientsRoute
  LayoutAdminUsersRoute: typeof LayoutAdminUsersRoute
  LayoutAdminIndexRoute: typeof LayoutAdminIndexRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminIngredientsRoute: LayoutAdminIngredientsRoute,
  LayoutAdminUsersRoute: LayoutAdminUsersRoute,
  LayoutAdminIndexRoute: LayoutAdminIndexRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutShareTargetRoute: typeof LayoutShareTargetRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProfileUserIdRoute: typeof LayoutProfileUserIdRoute
  LayoutRecipesIdRoute: typeof LayoutRecipesIdRoute
  LayoutRecipesPublicRoute: typeof LayoutRecipesPublicRoute
  LayoutShoppingListsIdRoute: typeof LayoutShoppingListsIdRoute
  LayoutRecipesIndexRoute: typeof LayoutRecipesIndexRoute
  LayoutShoppingListsIndexRoute: typeof LayoutShoppingListsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutShareTargetRoute: LayoutShareTargetRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProfileUserIdRoute: LayoutProfileUserIdRoute,
  LayoutRecipesIdRoute: LayoutRecipesIdRoute,
  LayoutRecipesPublicRoute: LayoutRecipesPublicRoute,
  LayoutShoppingListsIdRoute: LayoutShoppingListsIdRoute,
  LayoutRecipesIndexRoute: LayoutRecipesIndexRoute,
  LayoutShoppingListsIndexRoute: LayoutShoppingListsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
