#!/usr/bin/env bash
# Write compose.dev.yml: compose.yml, with the backend image built from this
# checkout instead of pulled from GHCR.
#
# The dev environment is the one Coolify deploys by itself: its application
# tracks master with auto-deploy on, so it has to build what it runs. Staging
# and production never build — they pull the image release.yml publishes — so
# compose.yml stays pull-only and the build lives in this generated copy.
# Generating it, rather than keeping a second hand-written stack, is what keeps
# dev running the same services, limits and Coolify magic variables as the
# environments it previews.
#
# `--no-interpolate` keeps every ${VAR} for Coolify to fill in, and
# `--no-path-resolution` keeps the build context relative, so the file means
# the same thing on any machine.
#
#   scripts/generate-compose-dev.sh          rewrite compose.dev.yml
#   scripts/generate-compose-dev.sh --check  fail if it is out of date
set -euo pipefail

ROOT=$(cd -- "$(dirname -- "$0")/.." && pwd)
cd "$ROOT"

overlay=$(mktemp --suffix=.yml)
generated=$(mktemp --suffix=.yml)
trap 'rm -f "$overlay" "$generated"' EXIT

# Every service that runs the backend image. A local tag, and
# `pull_policy: build`, so Coolify builds it on every deploy instead of
# looking for it in a registry. ENVIRONMENT defaults to dev here, where
# compose.yml defaults it to production.
cat > "$overlay" <<'EOF'
services:
  backend:
    image: shop-n-cook-backend:dev
    pull_policy: build
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-dev}
  prestart:
    image: shop-n-cook-backend:dev
    pull_policy: build
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-dev}
EOF

# The merged stack, as this machine's Compose renders it.
render() {
  docker compose -p shop-n-cook "$@" \
    config --no-interpolate --no-path-resolution --no-normalize
}

if [ "${1:-}" = "--check" ]; then
  # Compared as Compose reads them, not as text: two Compose versions lay the
  # same stack out differently, and the file is only stale when its meaning is.
  committed=$(mktemp --suffix=.yml)
  trap 'rm -f "$overlay" "$generated" "$committed"' EXIT
  render -f compose.dev.yml > "$committed"
  render -f compose.yml -f "$overlay" > "$generated"
  if ! diff -u "$committed" "$generated"; then
    echo "::error file=compose.dev.yml::compose.dev.yml is out of date with compose.yml. Run scripts/generate-compose-dev.sh and commit the result."
    exit 1
  fi
  echo "compose.dev.yml is up to date."
else
  {
    echo "# GENERATED by scripts/generate-compose-dev.sh from compose.yml — do not edit."
    echo "# The dev environment's Coolify stack: compose.yml, built from source."
    render -f compose.yml -f "$overlay"
  } > "$generated"
  cp "$generated" compose.dev.yml
  echo "Wrote compose.dev.yml."
fi
