// This file is auto-generated by @hey-api/openapi-ts

/**
 * Which walking order to print a list in.
 *
 * Not a store: nobody shops at "Printable list". See ``layouts.py``.
 */
export type AisleLayout = 'supermarket' | 'market';

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_recipes_import_recipe_photos = {
    photos: Array<((Blob | File))>;
    language?: (string | null);
};

/**
 * How the user gets from our list into the store's basket.
 *
 * Exactly one of ``url`` / ``plan`` is set, selected by ``transport``. Both
 * transports share this one return type so the frontend branches once, in the
 * render layer, instead of everywhere.
 */
export type CartHandoff = {
    store_slug: string;
    transport: Transport;
    url?: (string | null);
    plan?: (CartPlan | null);
    unresolved_item_names?: Array<(string)>;
};

/**
 * A declarative, retailer-agnostic script the extension executes.
 *
 * The extension owns *how* (selectors, waits, retries) via its own adapter
 * keyed on ``store_slug``; the backend owns *what*. Keeping the selectors out
 * of the backend means a retailer redesign ships as an extension update, not
 * a backend deploy.
 */
export type CartPlan = {
    store_slug: string;
    origin: string;
    branch_id?: (string | null);
    entries?: Array<CartPlanEntry>;
};

/**
 * One line of work for the extension to perform on the retailer's site.
 */
export type CartPlanEntry = {
    sku?: (string | null);
    query: string;
    name: string;
    quantity: number;
    product_url?: (string | null);
    requested_quantity?: (number | null);
    requested_unit?: (Unit | null);
};

export type DeduplicateMerge = {
    kept: string;
    removed: Array<(string)>;
};

export type DeduplicateResponse = {
    dry_run: boolean;
    groups: Array<DeduplicateMerge>;
    removed_count: number;
};

export type Difficulty = 'easy' | 'medium' | 'hard';

/**
 * Which ingredients to price, and in what currency.
 *
 * An empty ``ingredient_ids`` means "everything without a curated price",
 * which is the common case after a bulk import.
 */
export type EstimatePricesRequest = {
    ingredient_ids?: Array<(string)>;
    currency?: string;
};

/**
 * A list to shop from by hand.
 *
 * Carries both a structured form (``groups``, for the app to render natively)
 * and a rendered one (``content``, to copy, print or send to someone else).
 * Producing both avoids the frontend having to reimplement the aisle ordering
 * just to show the same thing twice.
 */
export type ExportedList = {
    store_slug: string;
    store_name: string;
    format: ListExportFormat;
    groups?: Array<ExportedListGroup>;
    content?: string;
    item_count?: number;
    merged_line_count?: number;
};

export type ExportedListGroup = {
    category: IngredientCategory;
    items?: Array<ExportedListItem>;
};

export type ExportedListItem = {
    name: string;
    quantity: number;
    unit: Unit;
    note?: (string | null);
    merged_from?: number;
};

/**
 * What to compose, and the constraints it must respect.
 */
export type GenerateMenuRequest = {
    name?: (string | null);
    start_date: string;
    days?: number;
    meal_types?: Array<MealType>;
    servings?: (number | null);
    budget?: (number | string | null);
    require_vegan?: boolean;
    require_vegetarian?: boolean;
    require_gluten_free?: boolean;
    require_dairy_free?: boolean;
    max_prep_minutes?: (number | null);
    match_season?: boolean;
    include_public?: boolean;
    seed?: number;
};

export type HouseholdCreate = {
    name: string;
};

export type HouseholdInviteCreate = {
    email: string;
};

export type HouseholdInvitePublic = {
    id: string;
    email: string;
    expires_at: string;
    accepted_at?: (string | null);
};

export type HouseholdMemberPublic = {
    id: string;
    user_id: string;
    email: string;
    full_name?: (string | null);
    role: HouseholdRole;
    joined_at?: (string | null);
};

export type HouseholdPublic = {
    name: string;
    id: string;
    owner_id: string;
    created_at?: (string | null);
    members?: Array<HouseholdMemberPublic>;
    invites?: Array<HouseholdInvitePublic>;
    seats_remaining?: number;
};

/**
 * What a member may do.
 *
 * ``OWNER`` can rename the household, invite, and remove members;
 * ``MEMBER`` can see and edit the shared lists and plans but not the
 * membership itself.
 */
export type HouseholdRole = 'owner' | 'member';

export type HouseholdUpdate = {
    name?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * How a recipe entered the app, when it was not typed in by hand.
 */
export type ImportSource = 'url' | 'photo';

export type ImportUrlRequest = {
    url: string;
    language?: (string | null);
};

export type IngredientCategory = 'produce' | 'dairy' | 'meat' | 'seafood' | 'grains' | 'pantry' | 'spices' | 'beverages' | 'frozen' | 'bakery' | 'other';

export type IngredientCreate = {
    price_amount?: (number | string | null);
    price_quantity?: (number | null);
    price_unit?: (Unit | null);
    density_g_per_ml?: (number | null);
    piece_weight_g?: (number | null);
    name: string;
    category?: IngredientCategory;
    image_url?: (string | null);
};

export type IngredientPriceCreate = {
    price_amount: (number | string);
    price_quantity: number;
    price_unit: Unit;
    store_id: string;
};

export type IngredientPricePublic = {
    price_amount: string;
    price_quantity: number;
    price_unit: Unit;
    id: string;
    ingredient_id: string;
    store_id: string;
    store_name?: (string | null);
    updated_at?: (string | null);
};

export type IngredientPricesPublic = {
    data: Array<IngredientPricePublic>;
    count: number;
};

export type IngredientPublic = {
    price_amount?: (string | null);
    price_quantity?: (number | null);
    price_unit?: (Unit | null);
    density_g_per_ml?: (number | null);
    piece_weight_g?: (number | null);
    id: string;
    name: string;
    name_en: (string | null);
    category: IngredientCategory;
    image_url: (string | null);
    price_source?: (PriceSource | null);
    price_updated_at?: (string | null);
};

export type IngredientsPublic = {
    data: Array<IngredientPublic>;
    count: number;
};

export type IngredientUpdate = {
    price_amount?: (number | string | null);
    price_quantity?: (number | null);
    price_unit?: (Unit | null);
    density_g_per_ml?: (number | null);
    piece_weight_g?: (number | null);
    category?: (IngredientCategory | null);
    image_url?: (string | null);
};

/**
 * How an exported list renders its output.
 */
export type ListExportFormat = 'text' | 'markdown' | 'csv';

export type ListExportRequest = {
    format?: ListExportFormat;
    layout?: AisleLayout;
    category_labels?: ({
    [key: string]: (string);
} | null);
};

export type MealPlanCreate = {
    name: string;
    start_date: string;
    end_date: string;
};

export type MealPlanEntryCreate = {
    entry_date: string;
    meal_type?: MealType;
    servings?: number;
    recipe_id: string;
};

export type MealPlanEntryPublic = {
    entry_date: string;
    meal_type?: MealType;
    servings?: number;
    id: string;
    meal_plan_id: string;
    recipe_id: string;
    recipe_title: string;
    recipe_image_url?: (string | null);
    recipe_servings?: (number | null);
    prep_time_minutes?: (number | null);
    cook_time_minutes?: (number | null);
    estimated_cost?: (string | null);
    estimated_cost_per_serving?: (string | null);
};

export type MealPlanEntryUpdate = {
    entry_date?: (string | null);
    meal_type?: (MealType | null);
    servings?: (number | null);
    recipe_id?: (string | null);
};

export type MealPlanPublic = {
    name: string;
    start_date: string;
    end_date: string;
    id: string;
    owner_id: string;
    created_at?: (string | null);
    shopping_list_id?: (string | null);
    entries?: Array<MealPlanEntryPublic>;
    estimated_total?: (string | null);
    unpriced_entry_count?: number;
    currency?: string;
};

export type MealPlansPublic = {
    data: Array<MealPlanPublic>;
    count: number;
};

export type MealPlanUpdate = {
    name?: (string | null);
    start_date?: (string | null);
    end_date?: (string | null);
};

export type MealType = 'breakfast' | 'lunch' | 'dinner' | 'snack' | 'dessert' | 'drink' | 'other';

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type ParsedIngredient = {
    name: string;
    name_en?: (string | null);
    quantity: number;
    unit: Unit;
    notes?: (string | null);
    category?: IngredientCategory;
};

export type ParsedRecipe = {
    title: string;
    description?: (string | null);
    steps?: Array<ParsedStep>;
    servings?: (number | null);
    prep_time_minutes?: (number | null);
    cook_time_minutes?: (number | null);
    ingredients?: Array<ParsedIngredient>;
    source_url?: (string | null);
    image_url?: (string | null);
    seasons?: Array<Season>;
    is_vegan?: boolean;
    is_vegetarian?: boolean;
    is_gluten_free?: boolean;
    is_dairy_free?: boolean;
    kcal_per_serving?: (number | null);
    difficulty?: (Difficulty | null);
    meal_type?: (MealType | null);
    cuisine_type?: (string | null);
};

export type ParsedStep = {
    instruction: string;
    ingredient_names?: Array<(string)>;
};

/**
 * Where an ingredient's reference price came from.
 *
 * ``ESTIMATED`` rows were filled in by the LLM assist and may be overwritten
 * by a later estimate run; ``MANUAL`` rows were curated by a human and never
 * are.
 */
export type PriceSource = 'manual' | 'estimated';

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RecipeCreate = {
    title: string;
    description?: (string | null);
    servings?: (number | null);
    prep_time_minutes?: (number | null);
    cook_time_minutes?: (number | null);
    source_url?: (string | null);
    image_url?: (string | null);
    is_public?: boolean;
    seasons?: Array<Season>;
    is_vegan?: boolean;
    is_vegetarian?: boolean;
    is_gluten_free?: boolean;
    is_dairy_free?: boolean;
    kcal_per_serving?: (number | null);
    difficulty?: (Difficulty | null);
    meal_type?: (MealType | null);
    cuisine_type?: (string | null);
    ingredients?: Array<RecipeIngredientCreate>;
    steps?: Array<RecipeStepCreate>;
    import_consent?: boolean;
    import_source?: (ImportSource | null);
};

export type RecipeIngredientCreate = {
    ingredient_name: string;
    quantity: number;
    unit: Unit;
    notes?: (string | null);
    category?: (IngredientCategory | null);
    name_en?: (string | null);
};

export type RecipeIngredientPublic = {
    id: string;
    ingredient_name: string;
    quantity: number;
    unit: Unit;
    notes?: (string | null);
    estimated_cost?: (string | null);
};

export type RecipePublic = {
    title: string;
    description?: (string | null);
    servings?: (number | null);
    prep_time_minutes?: (number | null);
    cook_time_minutes?: (number | null);
    source_url?: (string | null);
    image_url?: (string | null);
    is_public?: boolean;
    seasons?: Array<Season>;
    is_vegan?: boolean;
    is_vegetarian?: boolean;
    is_gluten_free?: boolean;
    is_dairy_free?: boolean;
    kcal_per_serving?: (number | null);
    difficulty?: (Difficulty | null);
    meal_type?: (MealType | null);
    cuisine_type?: (string | null);
    id: string;
    owner_id: string;
    owner_name?: (string | null);
    created_at?: (string | null);
    ingredients?: Array<RecipeIngredientPublic>;
    steps?: Array<RecipeStepPublic>;
    estimated_cost?: (string | null);
    estimated_cost_per_serving?: (string | null);
    unpriced_ingredient_count?: number;
    currency?: string;
};

export type RecipesPublic = {
    data: Array<RecipePublic>;
    count: number;
};

export type RecipeStepCreate = {
    step_number: number;
    instruction: string;
    ingredient_indices?: Array<(number)>;
};

export type RecipeStepIngredientPublic = {
    recipe_ingredient_id: string;
    ingredient_name: string;
};

export type RecipeStepPublic = {
    id: string;
    step_number: number;
    instruction: string;
    ingredients?: Array<RecipeStepIngredientPublic>;
};

export type RecipeUpdate = {
    title?: (string | null);
    description?: (string | null);
    servings?: (number | null);
    prep_time_minutes?: (number | null);
    cook_time_minutes?: (number | null);
    source_url?: (string | null);
    image_url?: (string | null);
    is_public?: (boolean | null);
    ingredients?: (Array<RecipeIngredientCreate> | null);
    steps?: (Array<RecipeStepCreate> | null);
    seasons?: (Array<Season> | null);
    is_vegan?: (boolean | null);
    is_vegetarian?: (boolean | null);
    is_gluten_free?: (boolean | null);
    is_dairy_free?: (boolean | null);
    kcal_per_serving?: (number | null);
    difficulty?: (Difficulty | null);
    meal_type?: (MealType | null);
    cuisine_type?: (string | null);
};

/**
 * What one refresh actually managed to do.
 */
export type RefreshResult = {
    store_id: string;
    store_name: string;
    provider_slug: string;
    refreshed_count?: number;
    skipped?: Array<RefreshSkip>;
    stopped_early?: boolean;
};

export type RefreshSkip = {
    ingredient_name: string;
    reason: SkipReason;
};

export type ReimportRequest = {
    language?: (string | null);
};

export type Season = 'spring' | 'summer' | 'autumn' | 'winter';

export type ShoppingFrequency = 'weekly' | 'biweekly' | 'monthly';

export type ShoppingListCreate = {
    name: string;
    start_date?: (string | null);
    end_date?: (string | null);
};

export type ShoppingListItemCreate = {
    name: string;
    quantity: number;
    unit: Unit;
    is_checked?: boolean;
    notes?: (string | null);
};

export type ShoppingListItemPublic = {
    id: string;
    name: string;
    quantity: number;
    unit: Unit;
    is_checked: boolean;
    notes?: (string | null);
    estimated_cost?: (string | null);
};

export type ShoppingListItemUpdate = {
    quantity?: (number | null);
    unit?: (Unit | null);
    is_checked?: (boolean | null);
    notes?: (string | null);
};

export type ShoppingListPublic = {
    name: string;
    start_date?: (string | null);
    end_date?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
    items?: Array<ShoppingListItemPublic>;
    planned_recipes?: Array<ShoppingListRecipePublic>;
    estimated_total?: (string | null);
    unpriced_item_count?: number;
    currency?: string;
};

export type ShoppingListRecipePublic = {
    id: string;
    recipe_id: string;
    recipe_title: string;
    recipe_servings: (number | null);
    servings_planned: number;
    is_prepared: boolean;
    ingredients?: Array<RecipeIngredientPublic>;
    estimated_cost?: (string | null);
};

export type ShoppingListRecipeUpdate = {
    is_prepared?: (boolean | null);
    servings_planned?: (number | null);
};

export type ShoppingListsPublic = {
    data: Array<ShoppingListPublic>;
    count: number;
};

export type ShoppingListUpdate = {
    name?: (string | null);
    start_date?: (string | null);
    end_date?: (string | null);
};

/**
 * Why one ingredient came away without a refreshed price.
 */
export type SkipReason = 'no_match' | 'no_price' | 'no_pack_size' | 'store_unavailable';

export type StoreComparison = {
    data: Array<StoreComparisonEntry>;
    cheapest_store_id?: (string | null);
};

/**
 * What one shopping list would cost at one store.
 */
export type StoreComparisonEntry = {
    store_id: string;
    store_name: string;
    store_slug: string;
    currency: string;
    estimated_total?: (string | null);
    unpriced_item_count?: number;
};

export type StoreCreate = {
    name: string;
    slug: string;
    country?: string;
    currency?: string;
    price_index?: number;
    logo_url?: (string | null);
    is_active?: boolean;
    provider_slug?: (string | null);
};

/**
 * Ask a store to take delivery of one of the user's lists.
 */
export type StoreListRequest = {
    shopping_list_id: string;
    branch_id?: (string | null);
};

export type StorePublic = {
    name: string;
    slug: string;
    country?: string;
    currency?: string;
    price_index?: number;
    logo_url?: (string | null);
    is_active?: boolean;
    provider_slug?: (string | null);
    id: string;
    capabilities?: Array<(string)>;
    can_refresh_prices?: boolean;
    requires_extension?: boolean;
};

export type StoresPublic = {
    data: Array<StorePublic>;
    count: number;
};

export type StoreUpdate = {
    name?: (string | null);
    country?: (string | null);
    currency?: (string | null);
    price_index?: (number | null);
    logo_url?: (string | null);
    is_active?: (boolean | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * Who talks to the retailer.
 */
export type Transport = 'server' | 'extension' | 'offline';

export type Unit = 'g' | 'kg' | 'ml' | 'cl' | 'dl' | 'L' | 'piece' | 'tbsp' | 'tsp' | 'cup' | 'oz' | 'lb' | 'bunch' | 'pinch' | 'clove' | 'slice' | 'can' | 'package';

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserSettingsPublic = {
    household_size?: number;
    shopping_frequency?: ShoppingFrequency;
    budget_amount?: (string | null);
    currency?: string;
    preferred_store_id?: (string | null);
    id: string;
    user_id: string;
};

export type UserSettingsUpdate = {
    household_size?: (number | null);
    shopping_frequency?: (ShoppingFrequency | null);
    budget_amount?: (number | string | null);
    currency?: (string | null);
    preferred_store_id?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type HouseholdsReadMyHouseholdResponse = (HouseholdPublic);

export type HouseholdsDeleteMyHouseholdResponse = (Message);

export type HouseholdsUpdateMyHouseholdData = {
    requestBody: HouseholdUpdate;
};

export type HouseholdsUpdateMyHouseholdResponse = (HouseholdPublic);

export type HouseholdsCreateHouseholdData = {
    requestBody: HouseholdCreate;
};

export type HouseholdsCreateHouseholdResponse = (HouseholdPublic);

export type HouseholdsLeaveMyHouseholdResponse = (Message);

export type HouseholdsRemoveMemberData = {
    memberId: string;
};

export type HouseholdsRemoveMemberResponse = (Message);

export type HouseholdsInviteMemberData = {
    requestBody: HouseholdInviteCreate;
};

export type HouseholdsInviteMemberResponse = (HouseholdPublic);

export type HouseholdsRevokeInviteData = {
    inviteId: string;
};

export type HouseholdsRevokeInviteResponse = (Message);

export type HouseholdsAcceptInviteData = {
    inviteId: string;
};

export type HouseholdsAcceptInviteResponse = (HouseholdPublic);

export type IngredientPricesReadIngredientPricesData = {
    id: string;
};

export type IngredientPricesReadIngredientPricesResponse = (IngredientPricesPublic);

export type IngredientPricesUpsertIngredientPriceData = {
    id: string;
    requestBody: IngredientPriceCreate;
};

export type IngredientPricesUpsertIngredientPriceResponse = (IngredientPricePublic);

export type IngredientPricesDeleteIngredientPriceData = {
    id: string;
    storeId: string;
};

export type IngredientPricesDeleteIngredientPriceResponse = (Message);

export type IngredientsReadIngredientsData = {
    limit?: number;
    skip?: number;
};

export type IngredientsReadIngredientsResponse = (IngredientsPublic);

export type IngredientsCreateIngredientData = {
    requestBody: IngredientCreate;
};

export type IngredientsCreateIngredientResponse = (IngredientPublic);

export type IngredientsUpdateIngredientData = {
    id: string;
    requestBody: IngredientUpdate;
};

export type IngredientsUpdateIngredientResponse = (IngredientPublic);

export type IngredientsDeduplicateIngredientsData = {
    dryRun?: boolean;
};

export type IngredientsDeduplicateIngredientsResponse = (DeduplicateResponse);

export type IngredientsEstimateIngredientPriceRouteData = {
    currency?: string;
    id: string;
};

export type IngredientsEstimateIngredientPriceRouteResponse = (IngredientPublic);

export type IngredientsEstimateIngredientPricesRouteData = {
    requestBody: EstimatePricesRequest;
};

export type IngredientsEstimateIngredientPricesRouteResponse = (Message);

export type IngredientsFetchIngredientImageData = {
    id: string;
};

export type IngredientsFetchIngredientImageResponse = (IngredientPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MealPlansReadMealPlansData = {
    limit?: number;
    skip?: number;
};

export type MealPlansReadMealPlansResponse = (MealPlansPublic);

export type MealPlansCreateMealPlanData = {
    requestBody: MealPlanCreate;
};

export type MealPlansCreateMealPlanResponse = (MealPlanPublic);

export type MealPlansReadMealPlanData = {
    id: string;
};

export type MealPlansReadMealPlanResponse = (MealPlanPublic);

export type MealPlansUpdateMealPlanData = {
    id: string;
    requestBody: MealPlanUpdate;
};

export type MealPlansUpdateMealPlanResponse = (MealPlanPublic);

export type MealPlansDeleteMealPlanData = {
    id: string;
};

export type MealPlansDeleteMealPlanResponse = (Message);

export type MealPlansAddEntryData = {
    id: string;
    requestBody: MealPlanEntryCreate;
};

export type MealPlansAddEntryResponse = (MealPlanEntryPublic);

export type MealPlansUpdateEntryData = {
    entryId: string;
    id: string;
    requestBody: MealPlanEntryUpdate;
};

export type MealPlansUpdateEntryResponse = (MealPlanEntryPublic);

export type MealPlansDeleteEntryData = {
    entryId: string;
    id: string;
};

export type MealPlansDeleteEntryResponse = (Message);

export type MealPlansGenerateShoppingListData = {
    id: string;
    name?: (string | null);
};

export type MealPlansGenerateShoppingListResponse = (ShoppingListPublic);

export type MealPlansGenerateMenuRouteData = {
    requestBody: GenerateMenuRequest;
};

export type MealPlansGenerateMenuRouteResponse = (MealPlanPublic);

export type MealPlansSwapEntryData = {
    entryId: string;
    id: string;
    requestBody?: (GenerateMenuRequest | null);
};

export type MealPlansSwapEntryResponse = (MealPlanEntryPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RecipesReadPublicRecipesData = {
    cuisineType?: (string | null);
    difficulty?: (Difficulty | null);
    isDairyFree?: (boolean | null);
    isGlutenFree?: (boolean | null);
    isVegan?: (boolean | null);
    isVegetarian?: (boolean | null);
    limit?: number;
    mealType?: (MealType | null);
    ownerId?: (string | null);
    search?: (string | null);
    seasons?: (Array<Season> | null);
    skip?: number;
};

export type RecipesReadPublicRecipesResponse = (RecipesPublic);

export type RecipesReadRecipesData = {
    cuisineType?: (string | null);
    difficulty?: (Difficulty | null);
    isDairyFree?: (boolean | null);
    isGlutenFree?: (boolean | null);
    isVegan?: (boolean | null);
    isVegetarian?: (boolean | null);
    limit?: number;
    mealType?: (MealType | null);
    search?: (string | null);
    seasons?: (Array<Season> | null);
    skip?: number;
};

export type RecipesReadRecipesResponse = (RecipesPublic);

export type RecipesCreateRecipeData = {
    requestBody: RecipeCreate;
};

export type RecipesCreateRecipeResponse = (RecipePublic);

export type RecipesReadRecipeData = {
    id: string;
};

export type RecipesReadRecipeResponse = (RecipePublic);

export type RecipesUpdateRecipeData = {
    id: string;
    requestBody: RecipeUpdate;
};

export type RecipesUpdateRecipeResponse = (RecipePublic);

export type RecipesDeleteRecipeData = {
    id: string;
};

export type RecipesDeleteRecipeResponse = (Message);

export type RecipesReimportRecipeData = {
    id: string;
    requestBody: ReimportRequest;
};

export type RecipesReimportRecipeResponse = (RecipePublic);

export type RecipesImportRecipeUrlData = {
    requestBody: ImportUrlRequest;
};

export type RecipesImportRecipeUrlResponse = (ParsedRecipe);

export type RecipesImportRecipePhotosData = {
    formData: Body_recipes_import_recipe_photos;
};

export type RecipesImportRecipePhotosResponse = (ParsedRecipe);

export type ShoppingListsReadShoppingListsData = {
    limit?: number;
    skip?: number;
};

export type ShoppingListsReadShoppingListsResponse = (ShoppingListsPublic);

export type ShoppingListsCreateShoppingListData = {
    requestBody: ShoppingListCreate;
};

export type ShoppingListsCreateShoppingListResponse = (ShoppingListPublic);

export type ShoppingListsReadShoppingListData = {
    id: string;
};

export type ShoppingListsReadShoppingListResponse = (ShoppingListPublic);

export type ShoppingListsUpdateShoppingListData = {
    id: string;
    requestBody: ShoppingListUpdate;
};

export type ShoppingListsUpdateShoppingListResponse = (ShoppingListPublic);

export type ShoppingListsDeleteShoppingListData = {
    id: string;
};

export type ShoppingListsDeleteShoppingListResponse = (Message);

export type ShoppingListsAddItemData = {
    id: string;
    requestBody: ShoppingListItemCreate;
};

export type ShoppingListsAddItemResponse = (ShoppingListPublic);

export type ShoppingListsUpdateItemData = {
    id: string;
    itemId: string;
    requestBody: ShoppingListItemUpdate;
};

export type ShoppingListsUpdateItemResponse = (ShoppingListItemPublic);

export type ShoppingListsDeleteItemData = {
    id: string;
    itemId: string;
};

export type ShoppingListsDeleteItemResponse = (Message);

export type ShoppingListsAddRecipeData = {
    id: string;
    recipeId: string;
    servings?: (number | null);
};

export type ShoppingListsAddRecipeResponse = (ShoppingListPublic);

export type ShoppingListsCompareStoresData = {
    id: string;
};

export type ShoppingListsCompareStoresResponse = (StoreComparison);

export type ShoppingListsUpdatePlannedRecipeData = {
    id: string;
    plannedRecipeId: string;
    requestBody: ShoppingListRecipeUpdate;
};

export type ShoppingListsUpdatePlannedRecipeResponse = (ShoppingListRecipePublic);

export type ShoppingListsDeletePlannedRecipeData = {
    id: string;
    plannedRecipeId: string;
};

export type ShoppingListsDeletePlannedRecipeResponse = (Message);

export type ShoppingListsExportShoppingListRouteData = {
    id: string;
    requestBody: ListExportRequest;
};

export type ShoppingListsExportShoppingListRouteResponse = (ExportedList);

export type StoresReadStoresData = {
    activeOnly?: boolean;
    limit?: number;
    skip?: number;
};

export type StoresReadStoresResponse = (StoresPublic);

export type StoresCreateStoreData = {
    requestBody: StoreCreate;
};

export type StoresCreateStoreResponse = (StorePublic);

export type StoresUpdateStoreData = {
    id: string;
    requestBody: StoreUpdate;
};

export type StoresUpdateStoreResponse = (StorePublic);

export type StoresDeleteStoreData = {
    id: string;
};

export type StoresDeleteStoreResponse = (Message);

export type StoresRefreshStorePricesRouteData = {
    limit?: number;
    storeId: string;
};

export type StoresRefreshStorePricesRouteResponse = (RefreshResult);

export type StoresBuildStoreCartData = {
    requestBody: StoreListRequest;
    storeId: string;
};

export type StoresBuildStoreCartResponse = (CartHandoff);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UserSettingsReadUserSettingsResponse = (UserSettingsPublic);

export type UserSettingsUpdateUserSettingsData = {
    requestBody: UserSettingsUpdate;
};

export type UserSettingsUpdateUserSettingsResponse = (UserSettingsPublic);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);