name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify deployment
        run: curl -fsSL -X GET "${{ secrets.COOLIFY_DEPLOY_WEBHOOK }}"
